-- H110 v3 — Fase 2: the curated payer catalog (alcance v3 §3.4).
--
-- Default cycles, overridable per enrollment:
--   Medicare   60 months — CMS revalidates Part B enrollment every 5 years.
--   Medicaid   60 months — federal rule: states revalidate at least every 5 years.
--   Commercial 36 months — the usual (NCQA) recredentialing cycle.
--   Other      36 months.
-- Regional plans carry their state. Organizations add anything missing as
-- their own payer.

insert into public.cred_payers_global (name, payer_type, revalidation_months, state) values
  -- National commercial and Medicare Advantage carriers
  ('Aetna', 'commercial', 36, null),
  ('Cigna Healthcare', 'commercial', 36, null),
  ('UnitedHealthcare', 'commercial', 36, null),
  ('Humana', 'commercial', 36, null),
  ('Kaiser Permanente', 'commercial', 36, null),
  ('Anthem Blue Cross Blue Shield', 'commercial', 36, null),
  ('Oscar Health', 'commercial', 36, null),
  ('Ambetter (Centene)', 'commercial', 36, null),
  ('Molina Healthcare', 'commercial', 36, null),
  ('WellCare', 'commercial', 36, null),
  ('Health Net', 'commercial', 36, null),
  ('Devoted Health', 'commercial', 36, null),
  ('Alignment Health', 'commercial', 36, null),
  ('Clover Health', 'commercial', 36, null),
  -- Behavioral health carve-outs
  ('Optum Behavioral Health', 'commercial', 36, null),
  ('Evernorth Behavioral Health (Cigna)', 'commercial', 36, null),
  ('Carelon Behavioral Health', 'commercial', 36, null),
  ('Magellan Healthcare', 'commercial', 36, null),
  -- Blue Cross Blue Shield plans
  ('Blue Cross and Blue Shield of Alabama', 'commercial', 36, 'AL'),
  ('Blue Cross Blue Shield of Arizona', 'commercial', 36, 'AZ'),
  ('Arkansas Blue Cross and Blue Shield', 'commercial', 36, 'AR'),
  ('Blue Shield of California', 'commercial', 36, 'CA'),
  ('Florida Blue', 'commercial', 36, 'FL'),
  ('Blue Cross of Idaho', 'commercial', 36, 'ID'),
  ('Blue Cross and Blue Shield of Illinois', 'commercial', 36, 'IL'),
  ('Wellmark Blue Cross Blue Shield', 'commercial', 36, 'IA'),
  ('Blue Cross and Blue Shield of Kansas', 'commercial', 36, 'KS'),
  ('Blue Cross and Blue Shield of Louisiana', 'commercial', 36, 'LA'),
  ('CareFirst BlueCross BlueShield', 'commercial', 36, 'MD'),
  ('Blue Cross Blue Shield of Massachusetts', 'commercial', 36, 'MA'),
  ('Blue Cross Blue Shield of Michigan', 'commercial', 36, 'MI'),
  ('Blue Cross and Blue Shield of Minnesota', 'commercial', 36, 'MN'),
  ('Blue Cross and Blue Shield of Kansas City', 'commercial', 36, 'MO'),
  ('Blue Cross and Blue Shield of Montana', 'commercial', 36, 'MT'),
  ('Blue Cross and Blue Shield of Nebraska', 'commercial', 36, 'NE'),
  ('Horizon Blue Cross Blue Shield of New Jersey', 'commercial', 36, 'NJ'),
  ('Blue Cross and Blue Shield of New Mexico', 'commercial', 36, 'NM'),
  ('Excellus BlueCross BlueShield', 'commercial', 36, 'NY'),
  ('Blue Cross and Blue Shield of North Carolina', 'commercial', 36, 'NC'),
  ('Blue Cross and Blue Shield of Oklahoma', 'commercial', 36, 'OK'),
  ('Regence BlueCross BlueShield', 'commercial', 36, 'OR'),
  ('Highmark Blue Cross Blue Shield', 'commercial', 36, 'PA'),
  ('Independence Blue Cross', 'commercial', 36, 'PA'),
  ('Capital Blue Cross', 'commercial', 36, 'PA'),
  ('Blue Cross and Blue Shield of Rhode Island', 'commercial', 36, 'RI'),
  ('Blue Cross and Blue Shield of South Carolina', 'commercial', 36, 'SC'),
  ('BlueCross BlueShield of Tennessee', 'commercial', 36, 'TN'),
  ('Blue Cross and Blue Shield of Texas', 'commercial', 36, 'TX'),
  ('Blue Cross and Blue Shield of Vermont', 'commercial', 36, 'VT'),
  ('Premera Blue Cross', 'commercial', 36, 'WA'),
  ('Blue Cross Blue Shield of Wyoming', 'commercial', 36, 'WY'),
  -- Regional commercial plans
  ('EmblemHealth', 'commercial', 36, 'NY'),
  ('Harvard Pilgrim Health Care', 'commercial', 36, 'MA'),
  ('Tufts Health Plan', 'commercial', 36, 'MA'),
  ('Priority Health', 'commercial', 36, 'MI'),
  ('HealthPartners', 'commercial', 36, 'MN'),
  ('Medica', 'commercial', 36, 'MN'),
  ('Geisinger Health Plan', 'commercial', 36, 'PA'),
  ('UPMC Health Plan', 'commercial', 36, 'PA'),
  ('Presbyterian Health Plan', 'commercial', 36, 'NM'),
  ('SelectHealth', 'commercial', 36, 'UT'),
  ('Providence Health Plan', 'commercial', 36, 'OR'),
  ('Sentara Health Plans', 'commercial', 36, 'VA'),
  ('Baylor Scott & White Health Plan', 'commercial', 36, 'TX'),
  -- Multi-state Medicaid managed care
  ('Aetna Better Health', 'medicaid', 60, null),
  ('UnitedHealthcare Community Plan', 'medicaid', 60, null),
  ('Wellpoint (formerly Amerigroup)', 'medicaid', 60, null),
  ('AmeriHealth Caritas', 'medicaid', 60, null),
  ('CareSource', 'medicaid', 60, null),
  -- Medicare
  ('Medicare Part B (Original Medicare)', 'medicare', 60, null),
  ('Railroad Medicare (Palmetto GBA)', 'medicare', 60, null),
  -- Military and veterans
  ('TRICARE East (Humana Military)', 'other', 36, null),
  ('TRICARE West (TriWest Healthcare Alliance)', 'other', 36, null),
  ('VA Community Care Network (Optum)', 'other', 36, null),
  ('VA Community Care Network (TriWest)', 'other', 36, null),
  -- State Medicaid programs (fee-for-service)
  ('Alabama Medicaid', 'medicaid', 60, 'AL'),
  ('Alaska Medicaid', 'medicaid', 60, 'AK'),
  ('Arizona Medicaid (AHCCCS)', 'medicaid', 60, 'AZ'),
  ('Arkansas Medicaid', 'medicaid', 60, 'AR'),
  ('California Medicaid (Medi-Cal)', 'medicaid', 60, 'CA'),
  ('Colorado Medicaid (Health First Colorado)', 'medicaid', 60, 'CO'),
  ('Connecticut Medicaid (HUSKY Health)', 'medicaid', 60, 'CT'),
  ('Delaware Medicaid', 'medicaid', 60, 'DE'),
  ('District of Columbia Medicaid', 'medicaid', 60, 'DC'),
  ('Florida Medicaid', 'medicaid', 60, 'FL'),
  ('Georgia Medicaid', 'medicaid', 60, 'GA'),
  ('Hawaii Medicaid (Med-QUEST)', 'medicaid', 60, 'HI'),
  ('Idaho Medicaid', 'medicaid', 60, 'ID'),
  ('Illinois Medicaid', 'medicaid', 60, 'IL'),
  ('Indiana Medicaid', 'medicaid', 60, 'IN'),
  ('Iowa Medicaid', 'medicaid', 60, 'IA'),
  ('Kansas Medicaid (KanCare)', 'medicaid', 60, 'KS'),
  ('Kentucky Medicaid', 'medicaid', 60, 'KY'),
  ('Louisiana Medicaid', 'medicaid', 60, 'LA'),
  ('Maine Medicaid (MaineCare)', 'medicaid', 60, 'ME'),
  ('Maryland Medicaid', 'medicaid', 60, 'MD'),
  ('Massachusetts Medicaid (MassHealth)', 'medicaid', 60, 'MA'),
  ('Michigan Medicaid', 'medicaid', 60, 'MI'),
  ('Minnesota Medicaid (Medical Assistance)', 'medicaid', 60, 'MN'),
  ('Mississippi Medicaid', 'medicaid', 60, 'MS'),
  ('Missouri Medicaid (MO HealthNet)', 'medicaid', 60, 'MO'),
  ('Montana Medicaid', 'medicaid', 60, 'MT'),
  ('Nebraska Medicaid', 'medicaid', 60, 'NE'),
  ('Nevada Medicaid', 'medicaid', 60, 'NV'),
  ('New Hampshire Medicaid', 'medicaid', 60, 'NH'),
  ('New Jersey Medicaid (NJ FamilyCare)', 'medicaid', 60, 'NJ'),
  ('New Mexico Medicaid', 'medicaid', 60, 'NM'),
  ('New York Medicaid', 'medicaid', 60, 'NY'),
  ('North Carolina Medicaid', 'medicaid', 60, 'NC'),
  ('North Dakota Medicaid', 'medicaid', 60, 'ND'),
  ('Ohio Medicaid', 'medicaid', 60, 'OH'),
  ('Oklahoma Medicaid (SoonerCare)', 'medicaid', 60, 'OK'),
  ('Oregon Medicaid (Oregon Health Plan)', 'medicaid', 60, 'OR'),
  ('Pennsylvania Medicaid (Medical Assistance)', 'medicaid', 60, 'PA'),
  ('Rhode Island Medicaid', 'medicaid', 60, 'RI'),
  ('South Carolina Medicaid (Healthy Connections)', 'medicaid', 60, 'SC'),
  ('South Dakota Medicaid', 'medicaid', 60, 'SD'),
  ('Tennessee Medicaid (TennCare)', 'medicaid', 60, 'TN'),
  ('Texas Medicaid', 'medicaid', 60, 'TX'),
  ('Utah Medicaid', 'medicaid', 60, 'UT'),
  ('Vermont Medicaid (Green Mountain Care)', 'medicaid', 60, 'VT'),
  ('Virginia Medicaid (Cardinal Care)', 'medicaid', 60, 'VA'),
  ('Washington Medicaid (Apple Health)', 'medicaid', 60, 'WA'),
  ('West Virginia Medicaid', 'medicaid', 60, 'WV'),
  ('Wisconsin Medicaid (ForwardHealth)', 'medicaid', 60, 'WI'),
  ('Wyoming Medicaid', 'medicaid', 60, 'WY');
